version: "3.1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "./sql/conf.d:/etc/mysql/conf.d"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: snippetlord
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: snippetbox
    ports:
      - 9000:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080

  go:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
